name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: build
    env:
      GO111MODULE: on
      GOPROXY: https://proxy.golang.org
      XTEST: FALSE
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: ${{ github.ref }}
      - name: Setup
        uses: actions/setup-go@v6
        with:
          go-version: "1.26"
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
          args: --verbose
      - name: Run Tests
        run: go test -covermode=atomic -coverprofile=coverage.out $(go list ./...)
