name: PR Build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: build
    env:
      GO111MODULE: on
      GOPROXY: https://proxy.golang.org
      XTEST: FALSE

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup
        uses: actions/setup-go@v7
        with:
          go-version-file: './go.mod'

      - name: Lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
          args: --verbose

      - name: Test
        run: go test -covermode=atomic -coverprofile=coverage.out $(go list ./...)
