name: Tag Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  pull-requests: read

jobs:
  release:
    runs-on: ubuntu-latest
    environment: build
    env:
      GO111MODULE: on
      GOPROXY: https://proxy.golang.org
      XTEST: FALSE

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup
        uses: actions/setup-go@v7
        with:
          go-version-file: './go.mod'

      - name: Lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
          args: --verbose

      - name: Test
        run: go test -covermode=atomic -coverprofile=coverage.out $(go list ./...)

      - name: Build
        run: |
          mkdir dist
          GOOS=linux GOARCH=amd64 go build -o dist/xdemo-linux-amd64 .
          GOOS=linux GOARCH=arm64 go build -o dist/xdemo-linux-arm64 .

      - name: Generate Release Notes and Publish
        id: generate_release_notes
        uses: release-drafter/release-drafter@v7
        with:
          config-name: 'release-drafter.yml'
          name: "Release ${{ github.ref_name }}"
          tag: ${{ github.ref_name }}
          publish: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*
